name: Publish Rust Docs

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rust versions
        run:  rustup show

      - name: Rust cache
        uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0

      - name: Build rustdocs
        run:  SKIP_WASM_BUILD=1 cargo doc --all --no-deps

      - name: Make index.html
        run:  echo "<meta http-equiv=refresh content=0;url=cumulus_client_collator/index.html>" > ./target/doc/index.html

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
